[app]
title = Milk Accountant
package.name = milkaccountant
package.domain = org.kivy
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,ttf
version = 1.0
requirements = python3,kivy,arabic_reshaper,python-bidi
orientation = portrait
fullscreen = 1
android.permissions = INTERNET
android.ndk = 23b
android.api = 33
android.build_tools_version = 33.0.2
android.archs = armeabi-v7a
android.minapi = 21
android.ndk_api = 21
presplash.filename = %(source.dir)s/data/presplash.png
icon.filename = %(source.dir)s/data/icon.png
include_fonts = fonts/ArabicFont.ttf
